version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "spgp13/spg-p13-backend"
    ports:
      - "3001:3001"
    restart: always
    networks:
      - frontend

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "spgp13/spg-p13-frontend"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - frontend
    links:
      - "backend:be"
networks:
    frontend:
